### ISSUE TITLE
"make release" generates "calico-typha-amd64" rather than "calico-typha"

### ISSUE THREAD

**Issue by bcreane** [projectcalico/typha#102]
`make release` generates `calico-typha-amd64` rather than `calico-typha`

This seems like a side-effect of adding ppc64le support. I manually renamed the v3.0.0 binary to the `calico-typha`.

## Expected Behavior
Probably want to leave the amd64 name to be `calico-typha` and then append architecture-specific suffixes for PPC and other versions of the binary.

## Steps to Reproduce (for bugs)

1. make release VERSION=v3.0.1

## Your Environment

* Typha version (if using Typha binary directly `calico-typha --version`):
* And/Or, `calico/typha` container version (if running Typha in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Another alternative would be to stop treating `amd64` as special and just start attaching `calico-typha-amd64`.

**Comment by caseydavenport** [comment]
I think we can close this now since we don't ship the binaries themselves (just the docker images) and those are built correctly.
