### ISSUE TITLE
'make calico/typha' build image from source fails on RHEL 7.3 (Docker version: 1.11.2)

### ISSUE THREAD

**Issue by guirish** [projectcalico/typha#112]
## Expected Behavior

Typha image for  v0.6.0 should be build successfully from source on RHEL distro's even with non Docker CE versions. Issue occurs due to placing Dockerfile PATH before completing [OPTIONS] arguments while building typha image.

## Current Behavior

Build fails with below error message:
```bash
[root@mon1 typha]# make calico/typha
rm -rf docker-image/bin
mkdir -p docker-image/bin
cp bin/calico-typha-amd64 docker-image/bin/
docker build --pull -t calico/typha docker-image -f docker-image/Dockerfile
docker: "build" requires 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
make: *** [calico/typha] Error 1
```
## Possible Solution

Modify Makefile as follows
```diff
@@ -77,7 +77,7 @@ calico/typha: bin/calico-typha-$(ARCH)
        rm -rf docker-image/bin
        mkdir -p docker-image/bin
        cp bin/calico-typha-$(ARCH) docker-image/bin/
-       docker build --pull -t calico/typha$(ARCHTAG) docker-image -f docker-image/Dockerfile$(ARCHTAG)
+       docker build --pull -t calico/typha$(ARCHTAG) -f docker-image/Dockerfile$(ARCHTAG) docker-image

 # Pre-configured docker run command that runs as this user with the repo
 # checked out to /code, uses the --rm flag to avoid leaving the container
```

## Steps to Reproduce (for bugs)

1. Get Docker version : Docker version 1.11.2
2.  make calico/typha

## Your Environment

* Typha version (Building from source):v0.6.0
* Operating System and version:  Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by caseydavenport** [comment]
@guirish if you could submit a PR to fix this I'd be happy to merge it, thanks!

**Comment by caseydavenport** [comment]
This appears to be fixed now.

https://github.com/projectcalico/typha/blob/master/Makefile#L259
