### ISSUE TITLE
sync server should not log EOF errors

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/typha#14]
Typha logs have a lot of these warning messages:
```
{"log":"2017-06-09 18:38:39.422 [INFO][6] sync_server.go 312: Failed to read from client client=10.128.0.17:55058 connID=0x1021 error=EOF thread=\"read\"\n","stream":"stderr","time":"2017-06-09T18:38:39.423213605Z"}
```

It should not log a warning log for `EOF` since it's not really an error

**Comment by gunjan5** [comment]
BTW, this is a low priority issue

**Comment by fasaxc** [comment]
It doesn't that's an INFO log!  I think it's important for the log to capture why we're tearing down the connection.
