### ISSUE TITLE
Typha crash on K8s APIServer connection loss

### ISSUE THREAD

**Issue by gjtempleton** [projectcalico/typha#196]
## Expected Behavior

Typha should continue working as designed and handle the `server sent GOAWAY and closed the connection` message gracefully.

## Current Behavior

Typha crashes out completely with an error message as it appears to try to write a glog message to file:
```
2018-09-28 08:46:28.055 [INFO][7] health.go 150: Overall health summary=&health.HealthReport{Live:true, Ready:true}
E0928 08:46:34.961659       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=51, ErrCode=NO_ERROR, debug=""
E0928 08:46:34.961659       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=51, ErrCode=NO_ERROR, debug=""
log: exiting because of error: log: cannot create log: open /tmp/calico-typha.ip-10-41-165-254.unknownuser.log.ERROR.20180928-084634.7: no such file or directory
```

## Possible Solution

I've tried to find where in the codebase or dependencies this might be bubbling up from and can't seem to find it, therefore went down the workaround route.

Ensure there is a /tmp/ directory in the published Docker images.

Achieved in our K8s setup by adding (beginning of containers section is there for context on where in the spec we added it):

```
...
  containers:
  - image: calico-typha:v3.2.1
    name: calico-typha
+   volumeMounts:
+   - name: temp-volume
+     mountPath: /tmp/
+ volumes:
+ - name: temp-volume
...
```

## Steps to Reproduce (for bugs)

1. Restart a kube-apiserver pod/service which Typha pods with no volume mounted to /tmp/ are connected to
2. Watch to see that Typha errors and exits - K8s will restart it
3. Inspect logs of the Docker container that exited with exit code 2

## Context

Causes intermittent issues when we restart our `kube-apiserver` services to update certificates. We occasionally see the Typha pods crash out without the connected calico pods gracefully switching their connections.

## Your Environment

* Typha version (if using Typha binary directly `calico-typha --version`): 
* And/Or, `calico/typha` container version (if running Typha in a container): quay.io/calico/typha:v3.2.1
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.9.8
* Etcd version (if using etcd datastore driver): Using APIServer
* Operating System and version:
* Link to your project (optional):

**Comment by gjtempleton** [comment]
Hi @briansan thanks for picking this up.

The steps you've detailed seem like they should result in the same behaviour I've seen. I'll have a play with our test cluster this evening to make sure I can still reproduce and also see whether I can grab any more context around the conditions of this occurring.

Thanks!

**Comment by briansan** [comment]
@gjtempleton, no problem, it's my pleasure.
Yes, please let me know how it goes. I realized that I didn't report the versions that I used...
I tried with two different combinations: 
- k8s v1.12, calico + typha v3.2.3
- k8s v1.9.11, calico + typha v3.2.3

**Comment by gjtempleton** [comment]
Had a chance to play around with this further I can still reliably reproduce this behaviour as soon as I remove the temporary volume mount. I'm not particularly sure I've managed to grab any particularly useful extra information as it seems like it's just the non-graceful handling of the GOAWAY that causes all of the issues.

Things possibly relevant which I didn't previously mention:

* We run `kube-apiserver` as a Systemd controlled service, part of our certificate renewal is running `systemctl restart kube-apiserver`

* Generally restarting one kube-apiserver doesn't result in all 3 of our typha nodes crashing, but instead 1 to 2, this seems like each typha is independently deciding which APIserver to connect to and as soon as it restarts can't handle the GOAWAY

If there's any more environment information or data you think I could grab let me know and I'll give it a shot.

Meanwhile, here's the files logged to the /tmp volume mount I created to work around this:

There were a serious of other files (.INFO, .WARNING etc), but they all have the same contents 

`calico-typha.ERROR`:

```` 
cat /var/lib/kubelet/pods/da57f8c5-d7be-11e8-93d4-06dc87446cca/volumes/kubernetes.io~empty-dir/temp-volume/calico-typha.ERROR
Log file created at: 2018/10/24 19:03:25
Running on machine: **NODE_IP**
Binary: Built with gc go1.10.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1024 19:03:25.483190       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483209       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483227       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483234       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483240       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483246       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483252       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483266       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483273       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483279       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483292       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""
E1024 19:03:25.483316       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=129, ErrCode=NO_ERROR, debug=""

**Comment by briansan** [comment]
@gjtempleton just wanted to ping you again on this; if you could help me reproduce the `GOAWAY` response that `typha` is getting from the `kube-apiserver`, not only can i prove that mounting the /tmp dir will prevent the container crashing, i can also dig deeper into whether or not this is a larger issue across our different calico components since they all access `kube-apiserver` in the same manner as `typha`

**Comment by gjtempleton** [comment]
Hey @briansan ,

Sorry for the delay, too many plates spinning to dig further into this. I'm not sure how much more help I can be around the `GOAWAY` as it seems to be pretty easy for us to trigger on demand.

I assume the most helpful bit would be the systemd service file/config for our kube-apiserver setup, as such, see the below snippet (obviously replace the etcd URLs). I can also check to see whether we see the same behaviour with K8s version 1.9.11 with the same setup, should be able to give this a try this evening.
````
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=network.target kube-apiserver-cert.service kube-service-account-key-secret.service
Requires=kube-apiserver-cert.service kube-service-account-key-secret.service


[Service]
User=kubernetes
Group=kubernetes
ExecStart=/usr/bin/kube-apiserver \
  --anonymous-auth=false \
  --kubelet-client-certificate=/etc/kubernetes/ssl/kubelet.pem \
  --kubelet-client-key=/etc/kubernetes/ssl/kubelet-key.pem \
  --v=1 \
  --feature-gates=CustomPodDNS=true \
  --insecure-port=0 \
  --endpoint-reconciler-type=lease \
  --allow-privileged=true \
  --authorization-mode=RBAC \
  --cloud-provider=aws \
  --client-ca-file=/etc/kubernetes/ssl/kube-apiserver-ca.pem \
  --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem \
  --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem \
  "--etcd-servers=https://etcd-1.cluster2.k8s.local:<PORT1>,https://etcd-2.cluster2.k8s.local:<PORT1>,https://etcd-3.cluster2.k8s.local:<PORT1>,https://etcd-4.cluster2.k8s.local:<PORT1>,https://etcd-5.cluster2.k8s.local:<PORT1>" \
  "--etcd-quorum-read=true" \
  "--etcd-servers-overrides=/events#https://etcd-1.cluster2.k8s.local:<PORT2>;https://etcd-2.cluster2.k8s.local:<PORT2>;https://etcd-3.cluster2.k8s.local:<PORT2>;https://etcd-4.cluster2.k8s.local:<PORT2>;https://etcd-5.cluster2.k8s.local:<PORT2>" \
  --etcd-cafile=/etc/kubernetes/ssl/etcd-k8s-ca.pem \
  --etcd-certfile=/etc/kubernetes/ssl/etcd-k8s.pem \
  --etcd-keyfile=/etc/kubernetes/ssl/etcd-k8s-key.pem \
  --service-cluster-ip-range=10.254.0.0/16 \
  --admission-control=AlwaysPullImages,DenyEscalatingExec,SecurityContextDeny,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \
  --service-account-key-file=/etc/kubernetes/ssl/service-account-key.pem \
  --apiserver-count=3 \
  --storage-backend=etcd3 \
  --logtostderr=true
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target

**Comment by briansan** [comment]
@gjtempleton no worries at all. thanks for the followup.

I think I'm understanding why I'm unable to repro this, that you're running kube-apiserver as a systemd deployment while i'm running it as a kube container. When I update the key pair, typha will pick it up as a client at the same time that kube-apiserver picks it up on the server end so the TLS verification will always pass.

It's an interesting demonstration of how there are so many different ways to standup a kubernetes clusters and that wide variety of errors that are possible with one particular configuration and not possible at all with others. Just a random thought 😄 

At this point, I'm just itching to repro the `GOAWAY` so I'll do the systemd deployment, try to fix the issue, and let you know how it goes!

**Comment by gjtempleton** [comment]
Yeah, the endless combinations of ways to spin up a cluster is a constant ~nightmare~ joy in trying to track down where the root of a problem lies.

For what it's worth I've just given this a try in our testing cluster after updating to `1.9.11` and still see the `GOAWAY` being sent.

Also, for clarity, I don't actually need to touch the certs to trigger this failure, simply running `systemctl restart kube-apiserver` is enough to trigger the behaviour.

**Comment by fasaxc** [comment]
@gjtempleton Can you expand on 

> without the connected calico pods gracefully switching their connections.

It's normal for felix to restart to connect to a different Typha but the restart should be graceful in that we leave the dataplane state in place so packets should continue flowing and policy should continue to be enforced (although changes won't be applied until after the restart completes).  Just want to check that that's what you're seeing.  If existing connections drop during a restart, that's a bug that we'd want to investigate further.  Or, if felix isn't spotting that typha went down, that'd be something we'd want to dig in on too.  We have keepalives on that connection so we should detect typha going down.

**Comment by gjtempleton** [comment]
Hey @fasaxc,

I'm a bit rushed for time at the moment, but will see whether I can scrape together some graphs etc. of the behaviour we've seen and a reproducible scenario. We experienced an incident where the chain of events was roughly:

* We restart an API-Server systemd service for certificate rotation as described above
* We see the Typha pod connected to this API-Server instance crash out and restart due to the bug this thread documents - this Typha has 4 calico pods connected to it at this point
* These 4 Calico nodes don't shift their connections over to one of the other Typha pods and instead crash out

If it is reproducible this seems like a separate issue and #211 addresses the bug this ticket was originally raised for so I'll close this issue as resolved for now and raise a separate issue.

**Comment by fasaxc** [comment]
> We see the Typha pod connected to this API-Server instance crash out and restart due to the bug this thread documents - this Typha has 4 calico pods connected to it at this point

Agree, this is a bug; I think we have a patch in progress for that.

> These 4 Calico nodes don't shift their connections over to one of the other Typha pods and instead crash out

If Typha crashes, it's normal for Felix to die and restart.  That's by design; but after restart, it should connect to a new Typha and resync with it.  If you're wondering why we restart in that case, it's because it minimises the number of recovery paths that we have to maintain and ensures that the restart path can be tested very thoroughly.  That makes the solution more robust overall even if it's not quite what you're expecting.
