### ISSUE TITLE
Typha prints an [INFO] log every 200ms if BGPPeers CRD is not registered

### ISSUE THREAD

**Issue by vreon** [projectcalico/typha#271]
## Expected Behavior

Typha should be able to quietly handle the absence of the BGPPeers CRD, since it's not required if you're running Calico in policy-only mode (and it's not present in the install manifest).

## Current Behavior

Typha prints logs like the following:

```
2019-05-03 04:34:48.127 [INFO][6] watchercache.go 259: Failed to create watcher ListRoot="/calico/resources/v3/projectcalico.org/bgppeers" error=resource does not exist: BGPPeer with error: the server could not find the requested resource (get BGPPeers.crd.projectcalico.org) performFullResync=true
2019-05-03 04:34:48.327 [INFO][6] watchercache.go 259: Failed to create watcher ListRoot="/calico/resources/v3/projectcalico.org/bgppeers" error=resource does not exist: BGPPeer with error: the server could not find the requested resource (get BGPPeers.crd.projectcalico.org) performFullResync=true
2019-05-03 04:34:48.527 [INFO][6] watchercache.go 259: Failed to create watcher ListRoot="/calico/resources/v3/projectcalico.org/bgppeers" error=resource does not exist: BGPPeer with error: the server could not find the requested resource (get BGPPeers.crd.projectcalico.org) performFullResync=true
```

## Possible Solution

Creating the BGPPeers CRD mitigates the issue of course :)

## Steps to Reproduce (for bugs)

Install Calico for policy only, following the [Installing Calico for policy](https://docs.projectcalico.org/v3.7/getting-started/kubernetes/installation/other) guide. Use the [linked manifest on that page](https://docs.projectcalico.org/v3.7/manifests/calico-policy-only.yaml), following the instructions to enable Typha. Typha pods will begin printing those logs shortly after they start.

## Your Environment
* `calico/typha` container version: issue present in Calico + Typha from v3.3.0 to v3.7.0
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.13.4

**Comment by caseydavenport** [comment]
yeah, it would be nice to remove the need to install the CRD.

However, right now I think the BGPPeer CRD is required even in policy only mode in order to remove this log spam.

It's a bug that our manifests don't include the BGPPeer CRD.

If we want to remove the need for the CRD, we need a way to tell the syncer that it's not required. We still need to handle the case of "Required CRD is missing" by properly logging and reporting not-readiness.

The crux of the matter is that Typha doesn't know which CRDs are required for the particular configuration that you might be running, so it just requires the superset of all CRDs that might be needed.

**Comment by erwbgy** [comment]
We found that not adding at the additional CRDs resulted in typha continuously creating a large number of watches with a significant impact on apiserver performance in a cluster with lots of nodes.  

Can the canal.yaml manifest be updated with all of the CRDs?  The cluster role also needs updating to allow blockaffinities to be listed.

**Comment by fasaxc** [comment]
Might be enough to remove this if test: https://github.com/projectcalico/calico/blob/master/_includes/master/charts/calico/templates/kdd-crds.yaml#L15

**Comment by erwbgy** [comment]
Yes, that should fix the CRDs.  In rbac.yaml blockaffinities needs to be added: https://github.com/projectcalico/calico/blob/master/_includes/master/charts/calico/templates/rbac.yaml#L177

**Comment by fasaxc** [comment]
@erwbgy Feel up to putting up a PR?
