### ISSUE TITLE
Typha rebalancing causing calico errors

### ISSUE THREAD

**Issue by efilipov** [projectcalico/typha#291]
## Expected Behavior
Do not get (logs of) dropped connections all the time like:
```
2019-08-22 15:43:07.501 [WARNING][8] sync_server.go 465: Currently have too many connections, terminating one at random. connID=0x29f13 current=169 max=152 thread="numConnsGov"
2019-08-22 15:43:08.595 [WARNING][8] sync_server.go 465: Currently have too many connections, terminating one at random. connID=0x29f1d current=170 max=152 thread="numConnsGov"
2019-08-22 15:43:09.604 [WARNING][8] sync_server.go 465: Currently have too many connections, terminating one at random. connID=0x29f12 current=170 max=152 thread="numConnsGov"
2019-08-22 15:43:10.665 [WARNING][8] sync_server.go 465: Currently have too many connections, terminating one at random. connID=0x29ea2 current=170 max=152 thread="numConnsGov"
```
Calico pods not to show regular errors such as:
```
2019-08-22 16:11:11.392 [ERROR][46508] sync_client.go 260: Failed to read from server address="100.67.253.90:5473" connID=0x0 error=EOF type=""
2019-08-22 16:11:11.392 [WARNING][46508] daemon.go 593: Felix is shutting down reason="Connection to Typha failed"
2019-08-22 16:11:13.392 [FATAL][46508] daemon.go 642: Exiting. reason="Connection to Typha failed"
2019-08-22 16:11:13.392 [FATAL][46508] daemon.go 642: Exiting. reason="Connection to Typha failed"
2019-08-22 16:11:13.725 [WARNING][47615] int_dataplane.go 354: Failed to query VXLAN device error=Link not found
2019-08-22 16:11:15.515 [WARNING][47615] health.go 190: Reporter failed readiness checks name="int_dataplane" reporter-state=&health.reporterState{name:"int_dataplane", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf4fcd8870ad67e7, ext:400127462, loc:(*time.Location)(0x2c441e0)}}
2019-08-22 16:11:15.515 [WARNING][47615] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf4fcd8876e08d3e, ext:504142727, loc:(*time.Location)(0x2c441e0)}}
```

## Current Behavior
Above logs are visible on all of tour 3 typha pods at about the same time.

## Possible Solution
Possibly, increasing upper and/or lower limit of Typha connections via `TYPHA_MAXCONNECTIONSLOWERLIMIT` and `TYPHA_MAXCONNECTIONSUPPERLIMIT` env vars

## Steps to Reproduce (for bugs)
1. Get an active cluster with ~250 nodes
2. Run Calico + Typha with default settings
3. Check Typha logs

## Context
We haven't yet proven any specific application problem is due the connection drops as of yet, though there are regular failures for calico pods.

## Your Environment
 * ~250 node cluster of Kubernetes 1.13.9 on AWS
* Calico CNI + container calico-typha:v3.7.3
* CentOS 7.6.1810 with kernel 5.2.8-1.el7.elrepo.x86_64

**Comment by caseydavenport** [comment]
@efilipov at 250 nodes it's likely you'll want to have more than 3 typha instances. Increasing that number would reduce the number of nodes each has to service which would help with this issue as well. Is that workable?

**Comment by caseydavenport** [comment]
> We recommend at least one replica for every 200 nodes and no more than 20 replicas. In production, we recommend a minimum of three replicas to reduce the impact of rolling upgrades and failures.

Hm, I suppose the documentation does suggest this is fine.

I would have expected this to eventually settle to a steady state. But you're seeing this rebalancing behavior persist indefinitely?

**Comment by matthias50** [comment]
@caseydavenport, I work with @efilipov . I'm a bit confused about the suggestion to add more Typha replicas. As you mentioned, the docs say to have one replica per 200 nodes. Since we have 3 replicas, doesn't that mean we are good for up to 600 nodes?

**Comment by caseydavenport** [comment]
> Since we have 3 replicas, doesn't that mean we are good for up to 600 nodes?

Yeah, sorry - I corrected myself in the second comment. I think you should be fine with three. I'm still not sure I understand the situation. Are you seeing consistent error messages suggesting that Calico nodes are being forced to rebalance to other typhas? Or does it eventually reach steady-state?

**Comment by efilipov** [comment]
@caseydavenport , yes, that's indeed the case - the messages of dropped connections persist both for the Typha and the Calico instances. Balance is not reached.

Would you expect any adverse effects of having TYPHA_MAXCONNECTIONSLOWERLIMIT increased to a point where re-balancing would not kick in (i.e. > number of nodes)?

**Comment by caseydavenport** [comment]
That might allow for all nodes to bunch up on one Typha, which could impact performance and reliability. 

>  terminating one at random. connID=0x29f13 current=169 max=152 thread="numConnsGov"

If you look at each Typha, do they all report having more connections than the max like in this log? Could you share the max that is being reported for each? There might be a bug in the way we're calculating the max connections.

**Comment by efilipov** [comment]
Here are logs from 3 different typha pods:
```
2019-08-26 08:54:32.917 [WARNING][8] sync_server.go 465: Currently have too many connections, terminating one at random. connID=0x72e2d current=143 max=132 thread="numConnsGov"
2019-08-26 08:55:02.789 [WARNING][8] sync_server.go 465: Currently have too many connections, terminating one at random. connID=0x73087 current=137 max=132 thread="numConnsGov"
2019-08-26 08:55:31.125 [WARNING][8] sync_server.go 465: Currently have too many connections, terminating one at random. connID=0x73071 current=133 max=132 thread="numConnsGov"
```
At that particular point in time, the cluster has 222 nodes.

**Comment by efilipov** [comment]
> That might allow for all nodes to bunch up on one Typha, which could impact performance and reliability.

I see Calico<->Typha essentially the same as the relation between kubelets<->kube-apiserver. Kubelets also initiate long-lasting connections, yet they only rely on the Service object that's fronting the kube-apiserver for balancing. And while the balance is not perfect, it is good enough.

What's more, I'd expect the multiple Typha pods to provide a level of redundancy, not just load balancing. If a single pod going down would cause the other two to get overloaded, then there really is no redundancy. Ideally, the Typha group should tolerate even two pods going away without a disruption to the cluster - which, in a group of 3, would mean that a single Typha should be able to handle all the traffic.

**Comment by efilipov** [comment]
> Are you sure the values you listed are from 3 different typhas?

I'm positive about it. I did not include the log/grep commands and put it all in one block for brevity. You can see that the reported number of connections is different across the 3 lines, though.

I saw the rebalancing mechanism, and it makes sense on the surface. In practice, however, I find rebalancing by killing the long-lived connection on the server side to be a bit extreme. 

I think it would be simpler to drop the concept of server-side rebalancing altogether and rely on the LoadBalancer/Service object to do its job of detecting healthy backends and distributing connections among them. Some configurable client-side (caico) max-connection-uptime parameter can be used to enable periodic reconnect. The main difference would be that the client can refresh the connection in a controlled manner, rather than panicking when connection gets unexpectedly killed by the server.

> The title for this issue I believe is still an issue we could improve on.

I'd be happy to change it if you have a suggestion.

**Comment by danigrmartinez** [comment]
Hello, everyone. We are having the same issue as described here. 
We are running calico 3.7, with linear autocalerScaler base on the number of nodes. 1 typha per 200 nodes. With a minimum of 3 replicas. In our case is always 3 replicas.

The issue is with the assumption in the [rebalance function](https://github.com/projectcalico/typha/blob/release-v3.9/pkg/k8s/rebalance.go#L99). It is assuming 1 connection per calico-node. But the sum of all active connection in our typha pod is always double of the number of nodes or calico-nodes pods.

This does not matter for cluster lower 165 nodes because of the `configParams.MaxConnectionsLowerLimit` is 100 by default.

Do you guys know any reason why calico is opening two connection to typha? I am going to investigate and update if I find the reason

**Comment by fasaxc** [comment]
I think @danigrmartinez has hit the nail on the head.  I think the issue here is that we recently made confd use Typha in addition to Felix so Typha's expecting one connection per node but there'll actually be two in a system that uses confd.

As a workaround, increasing TYPHA_MAXCONNECTIONSLOWERLIMIT should work fine.  To match what Typha should be doing, you could set it to `2*(1 + numNodes*120/(numTyphas-1)/100)`

**Comment by fasaxc** [comment]
> The main difference would be that the client can refresh the connection in a controlled manner, rather than panicking when connection gets unexpectedly killed by the server.

This was a design choice.  The Typha interface can't be easily refreshed against a different Typha so, rather than implement some tricky special-case logic to handle that, we restart Felix.  Felix is designed to restart gracefully and the more problems that we handle in that way, the more well tested and battle-hardened that restart logic gets.

Balancing by timeout isn't a crazy idea but, given the above design decision, we'd end up restarting every Felix say once per hour, which is fairly expensive on a large cluster.  The idea behind this approach is to rebalance fairly quickly after a rolling restart, which can concentrate the connections on a small number of Typhas.

We bypass kube-proxy here to avoid bootstrapping issues since Calico is at the same layer of the stack as kube-proxy, we don't want to depend on it being up.

**Comment by fasaxc** [comment]
Just remembered one of the details of the algorithm that's important here.  We only disconnect clients at a slow rate.  That means that, even if the algorithm goes wrong (as in this case), each client stays connected for several minutes at a time.  That's enough for it to keep making progress with only short blips while it reconnects.  It's a bit like having a max uptime measured in minutes.

**Comment by danigrmartinez** [comment]
> I think the issue here is that we recently made confd use Typha in addition to Felix so Typha's expecting one connection per node but there'll actually be two in a system that uses confd.

@fasaxc thanks for confirming. Could you point me to the docs about confd, I just found old documentation, nothing relevance from the last versions.

> As a workaround, increasing TYPHA_MAXCONNECTIONSLOWERLIMIT should work fine. To match what Typha should be doing, you could set it to 2*(1 + numNodes*120/(numTyphas-1)/100)

definitely that will work also we will set the autoscale to match the connection limits.

> That's enough for it to keep making progress with only short blips while it reconnects. It's a bit like having a max uptime measured in minutes.

Normally, run just fine. But we observed timeouts from the applications running on the cluster when there is a big scale-up.

**Comment by fasaxc** [comment]
> Could you point me to the docs about confd, I just found old documentation, nothing relevance from the last versions.

This is our fork of confd that we use to generate BIRD configuration.  At this point it's quite a long way from upstream confd; it has a backend based on our datamodel.

> observed timeouts from the applications running on the cluster when there is a big scale-up.

When Felix restarts _new_ pods won't get connectivity until the restart completes but all existing pods should maintain connectivity.  Restart usually only takes a second or so.
