### ISSUE TITLE
Health does not start for specific DNS search domains

### ISSUE THREAD

**Issue by mskrocki** [projectcalico/typha#311]
Typha docker container with health enabled `HealthEnabled=true` fails to start when DNS search domain is set to "test.com".
Since typha docker image is based on "scratch" and the default Health address is "localhost" the service tries to resolve "localhost" name and do NOT use /etc/hosts. The reason /etc/hosts is not being used is because scratch does not contain /etc/nsswitch.conf file. (similar bug: https://github.com/kubernetes/kubernetes/issues/69195).
With search domain set to test.com, the name ends up being "localhost.test.com" which resolves to 69.172.200.109 address. This only happens for domains that have "localhost" name defined.

## Expected Behavior
The Health service should ALWAYS properly start on 127.0.0.1/::1 for the default "localhost".

## Current Behavior
Health service tries to start on 69.172.200.109 address when search domain is set to test.com.

## Possible Solution
a) make sure /etc/nsswitch.conf is present in docker image

## Steps to Reproduce (for bugs)
1. Set your system search domain to "test.com"
2. Try to deploy typha with Health enabled

## Context
This breaks k8s calico deployments, since Health service is usually enabled there.

## Your Environment

* Typha version (if using Typha binary directly `calico-typha --version`): latest
* And/Or, `calico/typha` container version (if running Typha in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 
* Etcd version (if using etcd datastore driver):
* Operating System and version: 
* Link to your project (optional):

**Comment by neiljerram** [comment]
@mskrocki @caseydavenport This looks fairly simple, but I'm not sure I fully understand
> when DNS search domain is set to "test.com"

yet.  Typha runs host-networked, so I think we're talking here about /etc/resolv.conf on the host node.  Right?

How do things work (as I believe we have Felix FV tests for this) when search domain is left empty?  Is it that golang does a DNS lookup for "localhost", but it's OK because DNS servers typically have a special case to respond "127.0.0.1" for "localhost"?

**Comment by neiljerram** [comment]
Ah, here's why the Felix FV tests don't catch this: https://github.com/projectcalico/felix/blob/master/fv/health_test.go#L201
```
				"-e", "TYPHA_HEALTHHOST=0.0.0.0",
```

**Comment by neiljerram** [comment]
> Typha runs host-networked, so I think we're talking here about /etc/resolv.conf on the host node

Sorry, that's wrong, I was confusing host-networked with host-filesystem.  So instead, I now think we're talking about the /etc/resolv.conf that Kubernetes establishes for the Typha pod based on https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config.
