### ISSUE TITLE
Calico typha doesn't work with BoundServiceAccountTokenVolume

### ISSUE THREAD

**Issue by lzang** [projectcalico/typha#313]
When GKE Alpha cluster is enabled, Typha pods fail to work after 1 hour because it doesn't reload service account tokens, while for GKE Alpha cluster, the BoundServiceAccountTokenVolume feature is enabled.

## Expected Behavior
Typha should continue working after be brought up.

## Current Behavior
After one hour, Typha log starts show the following error
```
2019-09-17 02:48:28.595 [ERROR][6] lookup.go 61: Failed to get Typha endpoint from Kubernetes error=Unauthorized
2019-09-17 02:48:28.596 [WARNING][6] rebalance.go 55: Failed to get number of Typhas error=<nil> numTyphas=0 thread="k8s-poll"
2019-09-17 02:48:28.599 [WARNING][6] rebalance.go 61: Failed to get number of nodes error=Unauthorized numNodes=0 thread="k8s-poll"
```

## Possible Solution
This is the same with issue https://github.com/kubernetes/kubernetes/issues/77651, and can be fixed by updating the client-go library.

## Steps to Reproduce (for bugs)
Bring a GKE alpha cluster with network policy enabled. 

## Your Environment

* Typha version (if using Typha binary directly `calico-typha --version`): 3.2.7
* And/Or, `calico/typha` container version (if running Typha in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used):1.13
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
This seems to have fixed the issue with Typha on master: https://github.com/projectcalico/libcalico-go/pull/1138

I'm also fixing a similar issue with the CNI plugin via this PR: https://github.com/projectcalico/node/pull/344
