### ISSUE TITLE
calico-typha false positive health-check when not accepting connections

### ISSUE THREAD

**Issue by wsbondie** [projectcalico/typha#345]
When calico-typha cannot receive connections from calico-node(s), the health-check states that calico-typha is healthy.

## Expected Behavior

calico-typha health-check fails when calico-nodes cannot connect due to an io timeout.

## Current Behavior

calico-typha is not accepting connections and the calico-node pods logs:

2019-11-28 06:51:48.973 [FATAL][90] client.go 165: Failed to connect to Typha error=dial tcp 100.67.253.90:5473: i/o timeout

## Possible Solution

We found by killing the typha PID the nodes were able to connect thereafter.

## Steps to Reproduce (for bugs)

We do not know what caused calico-typha to not accept connections from any new calico-node pods.

## Your Environment

* Typha version (if using Typha binary directly `calico-typha --version`): 
* And/Or, `calico/typha` container version (if running Typha in a container): calico-typha:v3.8.4
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.15.6
* Etcd version (if using etcd datastore driver): 3.3.10
* Operating System and version: CentOS 7
* Link to your project (optional):

**Comment by rafaelvanoni** [comment]
@wsbondie Could you increase the log level on typha and send us the log once you reproduce this issue? Anything about your setup that might help us reproduce this (number of pods, etc) ?
