### ISSUE TITLE
Detection mechanism for invalid NetworkPolicy

### ISSUE THREAD

**Issue by kfyharukz** [projectcalico/typha#356]
## Expected Behavior

When an invalid NetworkPolicy is applied, Calico typha should give a notification to users.

## Current Behavior

In typha's logging, when an invalid NetworkPolicy is applied, typha outputs the messages like follows:
```
2020-03-27 04:15:25.496 [WARNING][11] validation_filter.go 57: Validation failed; treating as missing error=error with field DstPorts = '[3128]' (rules that specify ports must set protocol to TCP or UDP) key=Policy(name=sandbox/squid-allow) value=order:1001,selector:"projectcalico.org/namespace == 'sandbox'",inbound:,outbound:allow to ports 3128 selector "(has(projectcalico.org/namespace)) && (app.kubernetes.io/name == 'squid')",untracked:false,pre_dnat:false,apply_on_forward:true,types:egress
```
However, user cannot get any other notification, so it is hard to determine why the NetworkPolicy does not works.

## Possible Solution

I think there are some ways to notify that information to users:

1. Validation at API server
    - such as validating webhook or CRD level validation in k8s
2. Expose counter metrics of validation failure

Maybe, all orchestrators cannot provide the way 1, so the latter one is preferred, I think.

## Your Environment

* Typha version : 3.11.1
* Which orchestrator are you using: Kubernetes 1.16
* Operating System and version: CoreOS 2345.3.0

**Comment by spikecurtis** [comment]
How did you apply the policy?  If you use `calicoctl` to apply Calico policies, I'd expect the validation to be checked at that time.

**Comment by kfyharukz** [comment]
Thank you for your reply.
I'm using `kubectl` to apply Calico NetworkPolicy, so the validation by `calicoctl` does not work...

**Comment by spikecurtis** [comment]
It's not really designed to work that way today, but there is a request for enhancement open to support using `kubectl` for these resources https://github.com/projectcalico/calico/issues/2923

I'm going to close this issue as essentially a duplicate.
