### ISSUE TITLE
Typha stills not balancing well on v3.14.1

### ISSUE THREAD

**Issue by phspagiari** [projectcalico/typha#384]
## Expected Behavior
Typha should balancing equal between typha replicas the current active connections to avoid overload in one specific pod.

## Current Behavior
Our typha was suffering from the well described rebalancing issues #291 when we are running under v3.9. We updated our stack to v3.14.1 to fix this issue. Just to clarify, we are facing the exactly problem described on #291 and isn't similar of this one, running under v3.9 we got the same log lines and the same weird behavior in our grafana dashboards and this isn't happening anymore.

We are suffering from a kind of "sticky" session that make our typha always unbalanced, like this:
![image](https://user-images.githubusercontent.com/968339/88246998-9d8fb380-cc72-11ea-80d7-5f6ab7013f3b.png)
If we do a new rollout, another pod will be the one with the majority active connections and this results in a lot of latency peaks, like this:
![image](https://user-images.githubusercontent.com/968339/88247115-f8c1a600-cc72-11ea-8e25-f370bd7f6f6a.png)

There's no ERROR or WARNING logs on typha (in any of the 3 instances), and I didn't find anything related to this problem looking at the calico-node logs.

I would like to add that we are using the [quick-start yaml](https://docs.projectcalico.org/archive/v3.14/manifests/calico.yaml) with very small changes, mostly related to MTU and prometheus metrics and of course enabling typha 😄 

## Your Environment
* And/Or, `calico/typha` container version (if running Typha in a container): v3.14.1
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): v1.17.4
* Etcd version (if using etcd datastore driver): 3.2.24
* Operating System and version: CoreOS-stable-2345.3.0

**Comment by caseydavenport** [comment]
@phspagiari are you actually encountering issues with workloads on your cluster, or is this more of an observation? 

114 connections is an entirely reasonable number of connection for a single Typha to handle - in fact, we've tested to well above that number without issue. I wouldn't expect perfect equal balancing between Typhas. The rebalancing algorithm is intended to reach a steady state and not churn connections unnecessarily, and so it has a tolerance for "imbalance" so long as the number of connections is acceptable. 

The original issue, if I understand it correct, was about the invalid WARNING logs, which were being emitted when they shouldn't have been.

CC @fasaxc in case I'm missing something!

**Comment by fasaxc** [comment]
Yes, this is working as designed; we only start balancing when there are more than 200 connections.  One typha can handle 500 connections without much problem.  FWIW, #291 was a bug where it was balancing (i.e. dropping connections) *too much*.  So, with bug #291 active you get better balancing but more logs about balancing.

When we rebalance a connection, felix restarts to connect to the new typha instance; that's probably the cause of glitches in your grafana.  The restart is nothing to worry about; felix should restart cleanly without dropping any packets.

100ms ping latency isn't too worrying; that means a round trip from typha to felix and back is completed in 100ms, indicating the felix instances can be at most 100ms behind typha. If you give typha more CPU, I'd expect that to go down (but keeping the cluster in sync to <100ms is pretty good, and a lot faster than kubernetes!)
