### ISSUE TITLE
 Typha causing APIServer crashes on larger Openshift clusters 

### ISSUE THREAD

**Issue by relyt0925** [projectcalico/typha#637]
On larger Openshift clusters: restarts of the typha operator cause really large memory spikes that result in the APIServer getting out of memory events and effects downstream components. In my cluster I currently have
12374 pods
225 nodes 
3314 services
```
kubectl get pods --all-namespaces -o wide --no-headers  | wc -l
   13274
   
   kubectl get nodes --no-headers | wc -l
     225

kubectl get services --all-namespaces --no-headers | wc -l
    3314
    
    Tylers-MacBook-Pro:~ tylerlisowski$ kubectl get secrets --all-namespaces -o wide --no-headers | wc -l
   19518

kubectl get cm --all-namespaces -o wide --no-headers | wc -l
   14238

```

Note we have a total of 3 typha pods in the cluster
```
kubectl get pods -n calico-system -l k8s-app=calico-typha
NAME                           READY   STATUS    RESTARTS   AGE
calico-typha-b66bc54df-44zk7   1/1     Running   0          28m
calico-typha-b66bc54df-shh4f   1/1     Running   0          28m
calico-typha-b66bc54df-vl7jp   1/1     Running   0          28m
```

Posting the associated graphs that show the behavior when restarting typha (I can replicate by simply doing `kubectl delete pods -n calico-system -l k8s-app=calico-typha`) and waiting some time
![Screen Shot 2021-08-03 at 3 43 24 PM](https://user-images.githubusercontent.com/7716924/128083524-c65660b2-c5bd-427e-98db-8558ac1f7852.png)

At the time of the restart the kube-apiserver memory doubles after the restart of the pods (goes up by 20+Gigs). 

The maximum size of the backing database if 4GB. It seems odd that on startup of typha it would result in over 20+GB of utilization when it's meant to be a single "pool" of connecting to the datastore for all the calico-node pods.

## Expected Behavior

Memory usage of the openshift apiserver on a restart of typha should not double. Typha should be able to download the data it needs in a controlled fashion that doesn't cause the APIServer to drastically change from a memory perspective. 

## Current Behavior
At startup of typha pods memory usage drastically increases for the kube-apiserver hosting the cluster (doubles). 

## Possible Solution
Potentially try and rate limit data download for larger clusters? Maybe look at watch optimizations? 

## Steps to Reproduce (for bugs)
1) Get large cluster. The scaling characteristics I put above are within Kubernetes maximums  and can be utilized for reference
2) Restart typha pods 
3) Watch memory of kube-apiserver while the calico-typha pods are starting up (takes about 10 minutes in my monitoring for results to be shown.)

## Context

This issue affects the availability of the kube-apiserver. It can lead to slower processing of other workloads, drastically slower kubectl request processing (to the point where the requests time out), and failure of other control plane components like scheduling of pods, failover of pods, etc. This is due to the fact that calico-typha is consuming all the resources from the kube-apiserver

## Your Environment

* Operating System and version:
* Link to your project (optional):

Cluster: Openshift 4.7.19 (4.7.19_1526_openshift IBM Cloud Openshift cluster)
Details about the scale of the cluster are listed at the top of the issue
Calico typha version:     image: registry.ng.bluemix.net/armada-master/calico/typha:v3.19.1

**Comment by relyt0925** [comment]
Could also be related to this:
projectcalico/typha#492

**Comment by relyt0925** [comment]
Another example of it consistently getting evicted and the restarts leading to increased API workload (the evictions where occurring on 4 core 16 gig nodes.
```
calico-typha-b66bc54df-25xch               0/1     Evicted   0          3d
calico-typha-b66bc54df-2vc2v               0/1     Evicted   0          3d
calico-typha-b66bc54df-2z4hp               0/1     Evicted   0          3d
calico-typha-b66bc54df-49pdt               1/1     Running   0          3h3m
calico-typha-b66bc54df-6bbq5               0/1     Evicted   0          3d3h
calico-typha-b66bc54df-9klcb               0/1     Evicted   0          3d
calico-typha-b66bc54df-br2mb               1/1     Running   0          3h3m
calico-typha-b66bc54df-c2692               0/1     Evicted   0          3d15h
calico-typha-b66bc54df-ft9ds               0/1     Evicted   0          3d15h
calico-typha-b66bc54df-hlvj2               0/1     Evicted   0          3d
calico-typha-b66bc54df-jq9xt               0/1     Evicted   0          3d
calico-typha-b66bc54df-nrh8l               0/1     Evicted   0          3d
calico-typha-b66bc54df-rwwz9               0/1     Evicted   0          3d
calico-typha-b66bc54df-sn5vs               0/1     Evicted   0          3d
calico-typha-b66bc54df-tm2ls               0/1     Evicted   0          3d
calico-typha-b66bc54df-tmn7x               1/1     Running   0          3h3m
calico-typha-b66bc54df-tqdwx               0/1     Evicted   0          3d
calico-typha-b66bc54df-vpt75               0/1     Evicted   0          3d
calico-typha-b66bc54df-zkjxs               0/1     Evicted   0          3d
```

**Comment by caseydavenport** [comment]
@relyt0925 thanks for the issue report - I'm taking a look into this right now. Had a couple of questions for you!

> Could also be related to this: #492

Yeah I agree that might exacerbate any issue. Do you happen to have any logs from one of the Typhas? That might show whether or not we're hitting the retry issue. 

> calico-typha-b66bc54df-zkjxs               0/1     Evicted   0          3d

Do you know why the typha pods are being evicted in the first place? Not necessarily a fix, but could be relevant information for diagnosing. 

I'm attempting to reproduce this on my side and will let you know where I get to.

**Comment by relyt0925** [comment]
@caseydavenport I think it was just due to the node they were on running out of memory on the spike these pods were seeing on the restart for a given period of time (maybe also tied into the load when calico-node pods were talking to it).

**Comment by relyt0925** [comment]
related issues on watch restarts driving large load:
https://github.com/kubernetes/kubernetes/issues/92506
https://github.com/kubernetes/kubernetes/issues/90339
https://github.com/kubernetes/kubernetes/issues/90179

**Comment by relyt0925** [comment]
Also something in the kubernetes community that should help with limiting what watches do on a given apiserver:
https://github.com/openshift/kubernetes/pull/773
(The change is slated to go into Kubernetes 1.22. Limits the amount of watches that can be initialized in a given period of time

**Comment by caseydavenport** [comment]
@relyt0925 I haven't been able to reproduce the symptoms you're describing on my own clusters yet, but we have identified a number of watch improvements that we think might help in your case. I have a draft PR with those improvements here that I am doing some testing on at the moment: https://github.com/projectcalico/libcalico-go/pull/1484

Once I'm done with my own testing, would you be alright testing out a dev build with those changes to see if it helps on your cluster?

**Comment by relyt0925** [comment]
yep you got it @caseydavenport !

**Comment by relyt0925** [comment]
I think ultimately the fix will be including watches in API Priority and Fairness but the optimizations will help until people can get to the version that includes those enhancements. It would also just result in this situation in calico failing on the watch and potentially rushing to create more connections due to the other issue.

**Comment by relyt0925** [comment]
so optimizations are still going to be good thank you!

**Comment by caseydavenport** [comment]
@relyt0925 I've pushed an operator build to `caseydavenport/operator:optimized-watches` that includes my changes. It's based on Calico v3.20 / operator v1.20, so I'd suggest starting with those manifests and simply replacing the operator image. Let me know if that's enough to give it a whirl!

**Comment by relyt0925** [comment]
that's good enough for me @caseydavenport will report results back

**Comment by fasaxc** [comment]
> API Priority and Fairness

@relyt0925 what are you looking for in terms of priority and fairness.  I feel like Calico is a cluster-critical component, we need to have high priority over hte API

**Comment by relyt0925** [comment]
@fasaxc sure I agree: however calico alone cannot cause massive apiserver spikes to the point where it exhausts all memory/CPU and leads to worse downstream affects (takes out all kube apis in general)

Right now the main problem being experienced in larger clusters is when api servers restart or a group of watches do a full refresh of their watch cache: the thunderous herd of all of them at scale cause drastic kube-apiserver memory spikes (like 6x typical usage and likely higher just at that point the apiservers get stopped after experiencing memoryPressure.)

There needs to be some way to limit the thunderous herd problem along with components in general just being concious of the load that these watches can put on the apiserver. 

I have done some preliminary testing with Casey's changes and I am unable to replicate the problem which is good!

**Comment by relyt0925** [comment]
it looks like this is coming in an upcoming release of calico so will close
